fix: Update Arq42 and DockerFile Scripts
eclipse-tractusx/vas-country-risk pull request #37
Opened 2023-10-27 13:59 UTC by fabiodmota

## Description
- Switched the shell interpreter from `bash` to `sh` in our scripts to enhance portability and reduce dependencies. This change helps ensure our scripts run reliably in environments where `bash` may not be available. All relevant scripts have been updated and tested to confirm compatibility with `sh`.
- Updated arq42 documentation

Fixed for issues:
Arq42 dosc:  https://github.com/eclipse-tractusx/vas-country-risk-backend/issues/30 
Script change: https://github.com/eclipse-tractusx/vas-country-risk/issues/22

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-27 14:01 UTC, fabiodmota commented
Please  review on topics and leave comment
@enzio-bot  on Arq42 documentation
@alexsilva-CGI on script change

2023-10-27 14:20 UTC, alexsilva-CGI approved these changes
Looks good to me

2023-10-31 17:50 UTC, fabiodmota commented on docs/Images/reportUpdate.png
I didn't understand; most of the images are referenced with just "image" and a date. Most of them were included in some documentation. What do you really suggest in this case?

2023-10-31 17:52 UTC, fabiodmota commented on docs/Arc42-Documentation.md
> +![saveChangesReport](../docs/Images/saveChangesReport.png)
No , the two images are from the same action , one is the first user action the second is a popup for changes 
https://github.com/catenax-ng/tx-vas-country-risk-frontend/blob/main/docs/Arc42-Documentation.md#dashboard-controller

2023-11-07 09:53 UTC, almadigabor requested changes

2023-11-07 09:53 UTC, almadigabor commented on Dockerfile
> +    apk upgrade
`apk upgrade` or any other package managed upgrades are not allowed. The reason is that these official base images are scanned by Docker Hub and the results are published afterwards. Changing the image this way would mean those scan results are no longer valid. If you have any issues with the current image, consider upgrading to a newer tag.

2023-11-07 10:12 UTC, almadigabor approved these changes

2023-11-07 10:25 UTC, merged